### ISSUE TITLE
Can't use viewer on iOS in app or safari or chrome

### ISSUE THREAD

**Issue by DavidFW1960** [hassio-addons/addon-log-viewer#5]
# Problem/Motivation
As per title - logviewer addon not working on iOS
> (Why the issue was filed)

## Expected behavior
Expect it to work. Works on Windows 10 PC with chrome perfectly
> (What you expected to happen)

## Actual behavior
Displays 'reconnecting' in bottom left and cycles to Retry in 3s counts down connecting etc
> (What actually happened)

## Steps to reproduce
Open chrome or ios app or safar1 on iOS
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

I installed Hass.io on a USB stick on Raspbian Stretch lite via dale3h's script. Works flawlessly. I am using a Pi3B (not a plus). Stretch is fully up-to-date (Used June image and updated everything before using the script)
Also running iOS 12 beta on latest public beta.

```
NFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2018-08-16T23:24:55.147Z logview:debug start tailing /config/home-assistant.log
2018-08-16T23:24:55.163Z logview:info listening on port 4277 (HTTP)
2018-08-16T23:30:50.822Z logview:info client connected from ::ffff:172.30.32.1
2018-08-16T23:35:35.051Z logview:info client connected from ::ffff:172.30.32.1
2018-08-16T23:49:24.876Z logview:info client connected from ::ffff:172.30.32.1
2018-08-17T01:56:45.878Z logview:info client connected from ::ffff:172.30.32.1
2018-08-17T02:04:43.315Z logview:info client connected from ::ffff:172.30.32.1
2018-08-17T03:49:06.434Z logview:info client connected from ::ffff:172.30.32.1
2018-08-17T03:49:36.380Z logview:info client connected from ::ffff:172.30.32.1
2018-08-17T05:01:59.974Z logview:info client connected from ::ffff:172.30.32.1
2018-08-17T07:33:53.994Z logview:info client connected from ::ffff:172.30.32.1
2018-08-17T07:36:09.655Z logview:info client connected from ::ffff:172.30.32.1
2018-08-18T00:30:25.730Z logview:info client connected from ::ffff:172.30.32.1
2018-08-18T01:36:46.873Z logview:info client connected from ::ffff:172.30.32.1
```

Also I don't know if this is related but I see this error in the HA log..

```
Log Details (ERROR)
Sat Aug 18 2018 11:35:45 GMT+1000 (Australian Eastern Standard Time)

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 230, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 297, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

I tried this using the add-on in an iFrame as well as direct.
I am also using caddy as a reverse proxy.
Tried via my duckdns as well as direct ipaddress

All methods accept the login username and password I set.

**Comment by frenck** [comment]
@DavidFW1960 This hasn't a high priority, sorry.
The intended use wasn't mobile since one often uses this during the development of the automation system. It is considered a nice-to-have feature at this point.

**Comment by DavidFW1960** [comment]
@frenck thanks for the response.
