### ISSUE TITLE
Ingress error upon loading Log viewer

### ISSUE THREAD

**Issue by Mariusthvdb** [hassio-addons/addon-log-viewer#82]
# Problem/Motivation

> (Why the issue was filed)

every time I open the Log viewer in a Mac Safari browser, (HA 2021.5b5 now, Home Assistant OS) these errors are logged (note this is for 1 click... and Chrome and Firefox are fine):
```
2021-05-02 14:16:50 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
    source_header = _init_header(request, token)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 187, in _init_header
    connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
2021-05-02 14:16:50 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
    source_header = _init_header(request, token)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 187, in _init_header
    connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
2021-05-02 14:16:50 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
    source_header = _init_header(request, token)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 187, in _init_header
    connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
2021-05-02 14:16:50 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
    source_header = _init_header(request, token)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 187, in _init_header
    connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
2021-05-02 14:16:50 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
    source_header = _init_header(request, token)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 187, in _init_header
    connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
```
## Expected behavior

> (What you expected to happen)

No error
## Actual behavior

> (What actually happened)

## Steps to reproduce

A mere click in the left side menu on Log viewer
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not an add-on issue, there is nothing I can change about the add-on to fix this. Please report you issue upstream. Thanks!

**Comment by Mariusthvdb** [comment]
consider it done https://github.com/home-assistant/core/issues/49986
